@startuml 
 ' left to right direction

rectangle SikkerSone as "FHI sikker sone" {
    component Kodeverk #line:black
}

rectangle NHN {
    component Persontjenesten #line:black
    component Helsepersonellregisteret  #line:black
    component HelseID #line:black
}

rectangle Apoteksystemer as "Apoteksystemer (Capgemini)" {
    queue FarmaPro #line:black
    folder Eik #line:black
}

rectangle Azure #line.dotted {
    folder AzureFilestore #line:black;line.dotted
}

rectangle Legemiddelverket {
    component FEST as "Forskrivnings- og ekspedisjonsstøtte (FEST)" #line:black
    component Apotekoversikt #line:black
}

!$SkjulEksterne=0
!$SkjulPiler=0

!if ($SkjulPiler) 
    skinparam ComponentBorderColor black 
    !$ApoteksimulatorStyle = "#line.dotted"
    !$GrunndataStyle = ""
    !$KontrollsidenStyle = ""
    !$MeldingsformidlerStyle = ""
    !$LoggingStyle = ""
    !$MeldingsmottakStyle = ""
    !$PasientregisterStyle = ""
    !$RekvirentregisterStyle = ""
    !$UtleveringslagerStyle = ""
    !$TilgangerStyle = ""
    !$VarseltjenesteStyle = ""
!else
    !$ApoteksimulatorStyle = "#line:blue;line.dotted"
    !$GrunndataStyle = "#line:royalblue"
    !$KontrollsidenStyle = "#line:red"
    !$LoggingStyle = "#line:black"
    !$MeldingsformidlerStyle = "#line:darkgreen"
    !$MeldingsmottakStyle = "#line:greenyellow"
    !$PasientregisterStyle = "#line:darkgrey"
    !$RekvirentregisterStyle = "#line:purple"
    !$TilgangerStyle = "#line:darkorange"
    !$UtleveringslagerStyle = "#line:gold"
    !$VarseltjenesteStyle = "#line:brown"
!endif

rectangle Legemiddelregisteret #aliceblue;line:blue;text:blue {
    component Apoteksimulator $ApoteksimulatorStyle
    component Grunndata $GrunndataStyle
    component Kontrollsiden $KontrollsidenStyle
    component Logging $LoggingStyle
    component Meldingsformidler $MeldingsformidlerStyle 
    component Meldingsmottak $MeldingsmottakStyle
    component Pasientregister $PasientregisterStyle
    component Rekvirentregister $RekvirentregisterStyle
    component Tilganger $TilgangerStyle
    component Utleveringslager $UtleveringslagerStyle
    component Varseltjeneste $VarseltjenesteStyle
}

/' Skjul eksterne'/
!if ($SkjulEksterne) 
    hide Kodeverk
    hide Persontjenesten
    hide Helsepersonellregisteret
    hide HelseID
    hide FarmaPro
    hide Eik
    hide AzureFilestore
    hide FEST
    hide Apotekoversikt
!endif


!if ($SkjulPiler)
    !$pil = "-[hidden]-"
!else
    !$pil = "-->"
!endif

Apoteksimulator $pil AzureFilestore $ApoteksimulatorStyle
Grunndata $pil Apotekoversikt $GrunndataStyle
Grunndata $pil FEST $GrunndataStyle
Grunndata $pil Kodeverk $GrunndataStyle
Kontrollsiden $pil Grunndata $KontrollsidenStyle
Kontrollsiden $pil HelseID $KontrollsidenStyle
Kontrollsiden $pil Logging $KontrollsidenStyle
Kontrollsiden $pil Meldingsmottak $KontrollsidenStyle
Kontrollsiden $pil Tilganger $KontrollsidenStyle
Kontrollsiden $pil Varseltjeneste $KontrollsidenStyle
Meldingsformidler $pil Eik $MeldingsformidlerStyle
Meldingsformidler $pil FarmaPro $MeldingsformidlerStyle
Meldingsformidler $pil Meldingsmottak $MeldingsformidlerStyle
Meldingsformidler $pil Pasientregister $MeldingsformidlerStyle
Meldingsformidler $pil Rekvirentregister $MeldingsformidlerStyle
Meldingsformidler $pil Utleveringslager $MeldingsformidlerStyle
Meldingsformidler $pil AzureFilestore $MeldingsformidlerStyle
Meldingsmottak $pil Grunndata $MeldingsmottakStyle
Pasientregister $pil Persontjenesten $MeldingsmottakStyle
Rekvirentregister $pil Helsepersonellregisteret $RekvirentregisterStyle
Utleveringslager $pil Grunndata $UtleveringslagerStyle
Varseltjeneste $pil Meldingsmottak $VarseltjenesteStyle
Varseltjeneste $pil Utleveringslager $VarseltjenesteStyle

@enduml
