@startuml Utleveringslager

left to right direction

!$DetaljertVisning=0


package Felles {
    object PasientlisteTilBehandling {
      🔑 Guid MeldingsId
    }

    object RekvirentlisteTilBehandling {
      🔑 Guid MeldingsId
    }

    object Utleveringsmelding {
      🔑 Guid MeldingsId
    }

    object Utlevering {
      🔑 int UtleveringsId
    }
    Utlevering --> "1" Utleveringsmelding
}


package Eik {
    object "RekvisisjonTilBehandling" as Eik_RekvisisjonTilBehandling #F0C0C0 {
      🔑 Guid RekvisisjonsId
    }
    Eik_RekvisisjonTilBehandling --> "1" Utleveringsmelding

    object "UtleveringTilBehandling" as Eik_UtleveringTilBehandling #F0C0C0 {
      🔑 Guid MeldingsId
      🔑 int UtleveringsnummerIMelding
    }
    Eik_UtleveringTilBehandling --> "1" Utleveringsmelding

    object "UtleveringFraRekvisisjon" as Eik_UtleveringFraRekvisisjon {
      🔑 int UtleveringsId
    }
    Eik_UtleveringFraRekvisisjon --> "1" Utlevering

    !if ($DetaljertVisning)
        object "UtlevertVare" as Eik_UtlevertVare {
        🔑 int UtlevertVareId
      }

      object "InstitusjonsIdentitet" as Eik_InstitusjonsIdentitet {
        🔑 int InstitusjonsIdentitetId
      }

      object "Rekvisisjon" as Eik_Rekvisisjon {
        🔑 Guid RekvisisjonId
      }
      Eik_Rekvisisjon --> "0..*" Eik_InstitusjonsIdentitet
      Eik_UtleveringFraRekvisisjon --> "1" Eik_UtlevertVare
    !endif


    object "UtleveringTilDyr" as Eik_UtleveringTilDyr {
      🔑 int UtleveringsId
    }
    Eik_UtleveringTilDyr --> "1" Utlevering

    !if ($DetaljertVisning)
      object "Apoteksystem" as Eik_Apoteksystem {
        🔑 int ApoteksystemId
      }
      object "Resept" as Eik_Resept {
        🔑 int ReseptId
      }
      object "UtleveringTilDyr_Kryptert" as Eik_UtleveringTilDyr_Kryptert #F0C0C0 {
        🔑 int UtleveringTilDyrUtleveringsId
      }
      Eik_UtleveringTilDyr --> "1" Eik_UtlevertVare
      Eik_UtleveringTilDyr --> "0..1" Eik_Resept
      Eik_UtleveringTilDyr *-- Eik_UtleveringTilDyr_Kryptert
      Eik_UtleveringTilDyr --> "0..1" Eik_Apoteksystem
    !endif

    object "UtleveringTilMenneske" as Eik_UtleveringTilMenneske {
      🔑 int UtleveringsId
    }
    Eik_UtleveringTilMenneske --> "1" Utlevering

    !if ($DetaljertVisning)
      object "Refusjon" as Eik_Refusjon {
        🔑 int UtleveringsId
      } 

      object "PasientFraApotek" as Eik_PasientFraApotek {
        🔑 int PasientFraApotekId
      }

      object "UtleveringTilMenneske_Kryptert" as Eik_UtleveringTilMenneske_Kryptert #F0C0C0 {
        🔑 int UtleveringTilMenneskeUtleveringsId
      }

      Eik_UtleveringTilMenneske --> "0..1" Eik_Apoteksystem
      Eik_UtleveringTilMenneske --> "1" Eik_UtlevertVare
      Eik_UtleveringTilMenneske --> "0..1" Eik_PasientFraApotek
      Eik_UtleveringTilMenneske *-- Eik_UtleveringTilMenneske_Kryptert
      Eik_UtleveringTilMenneske --> "0..1" Eik_Resept
      Eik_UtleveringTilMenneske --> Eik_Refusjon
    !endif

    !if ($DetaljertVisning)
      object "BestanddelAnnet_Kryptert" as Eik_BestanddelAnnet_Kryptert #F0C0C0 {
        🔑 int BestanddelAnnetId
      }

      object "BestanddelAnnet" as Eik_BestanddelAnnet {
        🔑 int BestanddelAnnetId
      }
      Eik_BestanddelAnnet *-- Eik_BestanddelAnnet_Kryptert

      object "LegemiddelMerkevare" as Eik_LegemiddelMerkevare {
        🔑 int LegemiddelMerkevareId
      }

      object "Legemiddelpakning_Kryptert" as Eik_Legemiddelpakning_Kryptert #F0C0C0 {
        🔑 int LegemiddelpakningId
      }

      object "Legemiddelpakning" as Eik_Legemiddelpakning {
        🔑 int LegemiddelpakningId
      }
      Eik_Legemiddelpakning *-- Eik_Legemiddelpakning_Kryptert

      object "LegemiddelVirkestoff" as Eik_LegemiddelVirkestoff {
      🔑 int LegemiddelVirkestoffId
      }

      object "BestanddelLegemiddel" as Eik_BestanddelLegemiddel {
        🔑 int BestanddelLegemiddelId
      }
      Eik_BestanddelLegemiddel --> "0..1" Eik_LegemiddelMerkevare
      Eik_BestanddelLegemiddel --> "0..1" Eik_LegemiddelVirkestoff
      Eik_BestanddelLegemiddel --> "0..1" Eik_Legemiddelpakning


      object "BestanddelVirkestoff" as Eik_BestanddelVirkestoff {
        🔑 int BestanddelVirkestoffId
      }
    !endif

    !if ($DetaljertVisning)
      object "LegemiddelMerkevare_Kryptert" as Eik_LegemiddelMerkevare_Kryptert #F0C0C0 {
        🔑 int LegemiddelMerkevareId
      }
      Eik_LegemiddelMerkevare *-- Eik_LegemiddelMerkevare_Kryptert

      object "LegemiddelVirkestoff_Kryptert" as Eik_LegemiddelVirkestoff_Kryptert #F0C0C0 {
        🔑 int LegemiddelVirkestoffId
      }
      Eik_LegemiddelVirkestoff *-- Eik_LegemiddelVirkestoff_Kryptert

      object "Legemiddelblanding_Kryptert" as Eik_Legemiddelblanding_Kryptert #F0C0C0 {
        🔑 int LegemiddelblandingId
      }

      object "Legemiddelblanding" as Eik_Legemiddelblanding {
      🔑 int LegemiddelblandingId
      }
      Eik_Legemiddelblanding *-- Eik_Legemiddelblanding_Kryptert
      Eik_Legemiddelblanding --> "0..*" Eik_BestanddelAnnet
      Eik_Legemiddelblanding --> "0..*" Eik_BestanddelVirkestoff
      Eik_Legemiddelblanding --> "0..*" Eik_BestanddelLegemiddel
    !endif

    !if ($DetaljertVisning)
      object "Resept_RekvirertVare_Kryptert" as Eik_Resept_RekvirertVare_Kryptert #F0C0C0 {
        🔑 int RekvirertVareReseptId
      }
      Eik_Resept *-- Eik_Resept_RekvirertVare_Kryptert

      object "Lokalvare_Kryptert" as Eik_Lokalvare_Kryptert #F0C0C0 {
        🔑 int LokalvareId
      }

      object "Lokalvare" as Eik_Lokalvare {
        🔑 int LokalvareId
      }

      Eik_Lokalvare *-- Eik_Lokalvare_Kryptert
      Eik_UtlevertVare --> "0..1" Eik_Lokalvare
      Eik_UtlevertVare --> "0..1" Eik_Legemiddelblanding

      Eik_Rekvisisjon --> "0..1" Eik_Apoteksystem
      Eik_Rekvisisjon --> "0..*" Eik_UtleveringFraRekvisisjon
    !endif
}


package FarmaPro {

  !if ($DetaljertVisning)
    object UtleveringslagerFarmaproHendelse

    object Hendelse {
      🔑 Guid HendelseId
    }
    Hendelse *-- UtleveringslagerFarmaproHendelse

    object Refusjon {
      🔑 int UtleveringsId
    }

    object KundenavnFraApotek #F0C0C0 {
      🔑 Guid RekvisisjonsId
    }

    object Institusjon {
      🔑 Guid RekvisisjonsId
    }
    Institusjon --> "0..1" KundenavnFraApotek
  !endif

    object Rekvisisjon {
      🔑 Guid RekvisisjonsId
    }
    Rekvisisjon --> "1" Utleveringsmelding

    !if ($DetaljertVisning)
      object RekvirentFraApotek
      Rekvisisjon *-- RekvirentFraApotek
      Rekvisisjon --> "0..1" Institusjon
    !endif

    object UtleveringTilDyr {
      🔑 int UtleveringsId
    }
    UtleveringTilDyr --> "1" Utlevering
    !if ($DetaljertVisning)
      object UtlevertVare
      UtleveringTilDyr *-- UtlevertVare
      object Resept
      UtleveringTilDyr *-- Resept
      object Dyreart
      UtleveringTilDyr *-- Dyreart
      object BruksveiledningTilDyr #F0C0C0 {
        🔑 int UtleveringTilDyrUtleveringsId
      }
      UtleveringTilDyr *-- BruksveiledningTilDyr
    !endif

      object UtleveringTilMenneske {
        🔑 int UtleveringsId      
      }
      UtleveringTilMenneske --> "1" Utlevering

    !if ($DetaljertVisning)
      UtleveringTilMenneske *-- UtlevertVare
      
      object PasientFraApotek      
      UtleveringTilMenneske *-- PasientFraApotek
      UtleveringTilMenneske *-- Resept    
      UtleveringTilMenneske --> "0..1" Refusjon

      object BruksveiledningTilMenneske #F0C0C0 {
        🔑 int UtleveringTilMenneskeUtleveringsId
      }
      UtleveringTilMenneske *-- BruksveiledningTilMenneske
    !endif

    object RekvisisjonTilBehandling {
      🔑 Guid RekvisisjonsId
    }
    RekvisisjonTilBehandling --> "1" Utleveringsmelding

    object RekvisisjonUtleveringTilBehandling {
      🔑 Guid MeldingsId
      🔑 int UtleveringsnummerIMelding
    }
    RekvisisjonUtleveringTilBehandling --> "1" Utleveringsmelding

    object UtleveringBasertPåRekvisisjon {
      🔑 int UtleveringsId      
    }
    UtleveringBasertPåRekvisisjon --> "1" Utlevering

    !if ($DetaljertVisning)
      UtleveringBasertPåRekvisisjon *-- UtlevertVare
    !endif

    object ReseptUtleveringTilBehandling  #F0C0C0 {
      🔑 Guid MeldingsId
      🔑 int UtleveringsnummerIMelding
    }
    ReseptUtleveringTilBehandling --> "1" Utleveringsmelding
}

@enduml