@startuml Utleveringslager

' left to right direction

!$DetaljertVisning=0


package Felles {
  
    !if ($DetaljertVisning)
      object Klassifikasjon {
        🔑 int KlassifikasjonId      
      }

    object KodeverkKode {
      🔑 int KodeverkKodeId      
    }

    !endif

    object PasientlisteTilBehandling {
      🔑 Guid MeldingsId
    }

    object RekvirentlisteTilBehandling {
      🔑 Guid MeldingsId
    }

    object Utleveringsmelding {
      🔑 Guid MeldingsId
    }

    object Utlevering {
      🔑 int UtleveringsId
    }
    Utlevering --> Utleveringsmelding
}


package Eik {

    object "UtleveringTilDyr" as Eik_UtleveringTilDyr {
      🔑 int UtleveringsId
    }
    Eik_UtleveringTilDyr --> Utlevering

    !if ($DetaljertVisning)
      Eik_UtleveringTilDyr --> Eik_UtlevertVare
      Eik_UtleveringTilDyr --> Eik_Resept
      Eik_UtleveringTilDyr --> Eik_UtleveringTil_Kryptert
      Eik_UtleveringTilDyr --> Eik_Apoteksystem
    !endif


    object "UtleveringTilMenneske" as Eik_UtleveringTilMenneske {
      🔑 int UtleveringsId
    }
    Eik_UtleveringTilMenneske --> Utlevering

    !if ($DetaljertVisning)
      Eik_UtleveringTilMenneske --> Eik_Apoteksystem
      Eik_UtleveringTilMenneske --> Eik_UtlevertVare
      Eik_UtleveringTilMenneske --> Eik_PasientFraApotek
      Eik_UtleveringTilMenneske --> Eik_UtleveringTilMenneske_Kryptert
      Eik_UtleveringTilMenneske --> Eik_Resept
      Eik_UtleveringTilMenneske --> Eik_Refusjon

      object "Refusjon" as Eik_Refusjon {
        🔑 int UtleveringsId
      } 
    !endif

    !if ($DetaljertVisning)
      object "BestanddelAnnet" as Eik_BestanddelAnnet {
        🔑 int BestanddelAnnetId
      }
      Eik_BestanddelAnnet --> Eik_BestanddelAnnet_Kryptert

      object "BestanddelLegemiddel" as Eik_BestanddelLegemiddel {
        🔑 int BestanddelLegemiddelId
      }
      Eik_BestanddelLegemiddel --> Eik_LegemiddelMerkevare
      Eik_BestanddelLegemiddel --> Eik_LegemiddelVirkestoff
      Eik_BestanddelLegemiddel --> Eik_Legemiddelpakning


      object "BestanddelVirkestoff" as Eik_BestanddelVirkestoff {
        🔑 int BestanddelVirkestoffId
      }
    !endif


    !if ($DetaljertVisning)
      object "Apoteksystem" as Eik_Apoteksystem {
        🔑 int ApoteksystemId
      }

    object "PasientFraApotek" as Eik_PasientFraApotek {
      🔑 int PasientFraApotekId
    }
    !endif


    !if ($DetaljertVisning)
      object "LegemiddelMerkevare" as Eik_LegemiddelMerkevare {
        🔑 int LegemiddelMerkevareId
      }
      Eik_LegemiddelMerkevare --> Eik_LegemiddelMerkevare_Kryptert

      object "LegemiddelMerkevare_Kryptert" as Eik_LegemiddelMerkevare_Kryptert #F0C0C0 {
        🔑 int LegemiddelMerkevareId
      }

      object "Legemiddelpakning" as Eik_Legemiddelpakning {
        🔑 int LegemiddelpakningId
      }
      Eik_Legemiddelpakning --> Eik_Legemiddelpakning_Kryptert

      object "Legemiddelpakning_Kryptert" as Eik_Legemiddelpakning_Kryptert #F0C0C0 {
        🔑 int LegemiddelpakningId
      }

      object "LegemiddelVirkestoff" as Eik_LegemiddelVirkestoff {
      🔑 int LegemiddelVirkestoffId
      }
      Eik_LegemiddelVirkestoff --> Eik_LegemiddelVirkestoff_Kryptert

      object "LegemiddelVirkestoff_Kryptert" as Eik_LegemiddelVirkestoff_Kryptert #F0C0C0 {
        🔑 int LegemiddelVirkestoffId
      }

    !endif

    !if ($DetaljertVisning)

    object "Resept" as Eik_Resept {
      🔑 int ReseptId
    }
    Eik_Resept *-- Eik_Resept_RekvirertVare_Kryptert

    object "Resept_RekvirertVare_Kryptert" as Eik_Resept_RekvirertVare_Kryptert #F0C0C0 {
      🔑 int RekvirertVareReseptId
    }


    !endif

'Resept
'UtlevertVare
'Rekvisisjon
'Legemiddelblanding
'Lokalvare
'InstitusjonsIdentitet
'UtleveringFraRekvisisjon
'
'Kryptert:
'Legemiddelblanding_Kryptert
'Lokalvare_Kryptert
'UtleveringTilDyr_Kryptert
'UtleveringTilMenneske_Kryptert
'BestanddelAnnet_Kryptert
'LegemiddelVirkestoff_Kryptert
'.Resept_RekvirertVare_Kryptert
'RekvisisjonTilBehandling
'UtleveringTilBehandling





    object "BestanddelAnnet_Kryptert" as Eik_BestanddelAnnet_Kryptert #F0C0C0 {
      🔑 Guid KryptertId
    }

    object "Legemiddelblanding_Kryptert" as Eik_Legemiddelblanding_Kryptert #F0C0C0 {
      🔑 Guid KryptertId
    }




    object "Lokalvare_Kryptert" as Eik_Lokalvare_Kryptert #F0C0C0 {
      🔑 Guid KryptertId
    }

    object "RekvisisjonAvventerProsessering" as Eik_RekvisisjonAvventerProsessering #F0C0C0 {
      🔑 Guid RekvisisjonsId
    }
    Eik_RekvisisjonAvventerProsessering --> Utleveringsmelding : MeldingsId

    object "UtleveringAvventerProsessering" as Eik_UtleveringAvventerProsessering #F0C0C0 {
      🔑 Guid MeldingsId
      🔑 int UtleveringsnummerIMelding
    }
    Eik_UtleveringAvventerProsessering --> Utleveringsmelding : MeldingsId

    object "UtleveringTil_Kryptert" as Eik_UtleveringTil_Kryptert #F0C0C0 {
      🔑 Guid KryptertId
    }

    object "Legemiddelblanding" as Eik_Legemiddelblanding {
      🔑 Guid LegemiddelblandingId
    }
    Eik_Legemiddelblanding --> Eik_Legemiddelblanding_Kryptert : KryptertFeltId


    object "Lokalvare" as Eik_Lokalvare {
      🔑 Guid LokalvareId
    }
    Eik_Lokalvare --> Eik_Lokalvare_Kryptert : KryptertId

    object "UtlevertVare" as Eik_UtlevertVare {
      🔑 Guid UtlevertVareId
    }
    Eik_UtlevertVare --> "0..1" Eik_Lokalvare : LokalvareId
    Eik_UtlevertVare --> "0..1" Eik_Legemiddelblanding : LegemiddelblandingId


    object "Rekvisisjon" as Eik_Rekvisisjon {
      🔑 Guid RekvisisjonId
    }
    Eik_Rekvisisjon --> "0..1" Eik_Apoteksystem : ApoteksystemId

    object "InstitusjonsIdentitet" as Eik_InstitusjonsIdentitet {
      🔑 Guid InstitusjonsIdentitetId
    }
    Eik_InstitusjonsIdentitet --> "0..1" Eik_Rekvisisjon : RekvisisjonId


    object "Kodeverk_FeltOid" as Eik_Kodeverk_FeltOid {
      🔑 string Feltnavn
      🔑 int OId
    }




    object "UtleveringFraRekvisisjon" as Eik_UtleveringFraRekvisisjon {
      🔑 int UtleveringsId
    }
    Eik_UtleveringFraRekvisisjon --> Utlevering : UtleveringsId
    Eik_UtleveringFraRekvisisjon --> Eik_Rekvisisjon : RekvisisjonId
    Eik_UtleveringFraRekvisisjon --> Eik_UtlevertVare : UtlevertVareId



    


}


package FarmaPro {

  !if ($DetaljertVisning)
    object Hendelse {
      🔑 Guid HendelseId
    }
    object UtleveringslagerFarmaproHendelse
    Hendelse *-- UtleveringslagerFarmaproHendelse

    object Refusjon {
      🔑 int UtleveringsId
    }

    object KundenavnFraApotek #F0C0C0 {
      🔑 Guid RekvisisjonsId
    }

    object Institusjon {
      🔑 Guid RekvisisjonsId
    }
    Institusjon --> KundenavnFraApotek : RekvisisjonsId
  !endif

    object Rekvisisjon {
      🔑 Guid RekvisisjonsId
    }
    Rekvisisjon --> Utleveringsmelding

    !if ($DetaljertVisning)
      object RekvirentFraApotek
      Rekvisisjon *-- RekvirentFraApotek
      Rekvisisjon --> Institusjon
    !endif

    object UtleveringTilDyr {
      🔑 int UtleveringsId
    }
    UtleveringTilDyr --> Utlevering
    !if ($DetaljertVisning)
      object UtlevertVare
      UtleveringTilDyr *-- UtlevertVare
      object Resept
      UtleveringTilDyr *-- Resept
      object Dyreart
      UtleveringTilDyr *-- Dyreart
      object BruksveiledningTilDyr #F0C0C0
      UtleveringTilDyr *-- BruksveiledningTilDyr
    !endif

      object UtleveringTilMenneske {
        🔑 int UtleveringsId      
      }
      UtleveringTilMenneske --> Utlevering

    !if ($DetaljertVisning)
      UtleveringTilMenneske *-- UtlevertVare
      object PasientFraApotek
      UtleveringTilMenneske *-- PasientFraApotek
      UtleveringTilMenneske *-- Resept    
      UtleveringTilMenneske --> Refusjon
      object BruksveiledningTilMenneske #F0C0C0
      UtleveringTilMenneske *-- BruksveiledningTilMenneske
    !endif

    object RekvisisjonTilBehandling {
      🔑 Guid RekvisisjonsId
    }
    RekvisisjonTilBehandling --> Utleveringsmelding

    object RekvisisjonUtleveringTilBehandling {
      🔑 Guid MeldingsId
      🔑 int UtleveringsnummerIMelding
    }
    RekvisisjonUtleveringTilBehandling --> Utleveringsmelding

    object UtleveringBasertPåRekvisisjon {
      🔑 int UtleveringsId      
    }
    UtleveringBasertPåRekvisisjon --> Utlevering

    !if ($DetaljertVisning)
      UtleveringBasertPåRekvisisjon *-- UtlevertVare
    !endif

    object ReseptUtleveringTilBehandling  #F0C0C0 {
      🔑 Guid MeldingsId
      🔑 int UtleveringsnummerIMelding
    }
    ReseptUtleveringTilBehandling --> Utleveringsmelding

}




@enduml